version: "3.9"
services:
  backend:
    build: .
    expose:
      - 8000
    ports:
      - "8000:8000"
    command: "gunicorn -b 0.0.0.0:8000 app:app"
    links:
      - redis
  worker:
    build: .
    command: "celery -A celery_entrypoint worker"
    links:
      - redis
  redis:
    image: redis