openapi: 3.0.3
info:
  title: "CUGetReg Computation Backend"
  version: 0.0.1
paths:
  "/" :
    get:
      description: "Display Hello World"
      responses:
        "200":
          "description": "Hello World"
  "/api/suggest/courses":
    post:
      description: "Get recommended course from given selected course"
      requestBody:
        content:
          "application/json":
                schema:
                  type: object
                  properties:
                    selectedCourse:
                      type: array
                      items:
                        $ref: "#/components/schemas/CourseVal"
      responses:
        "201":
          description: "H"
          content:
            "application/json":
              schema:
                type: object
                properties:
                  suggestions:
                    type: array
                    items:
                      $ref: "#/components/schemas/CourseVal"
components:
  schemas:
   CourseVal:
     type: "object"
     properties:
       courseId:
         type: string
         example: "2110101"
       studyProgram:
         type: string
         example: "S"

servers:
  - url: "http://localhost:5000"